### ISSUE TITLE
Linking Struo premade db to Humann2

### ISSUE THREAD

**Issue by jnesme** [leylabmpi/Struo#1]
Dear devs, thanks a lot for and much needed tool.

I wanted to use your premade Humann2 database based on GTDBrs89 - but I must miss something obvious as I can't figure how to make Humann2 accept these (using --nucleotid-db and --protein-db )

It's indeed expecting ChocoPhlan type database with individual species genomes in separate *fa.gz files ?

Sorry if I'm missing something obvious :/

**Comment by nick-youngblut** [comment]
I've added an example humann2 run to the README. Please re-open this issue if you are still having problems.

**Comment by jnesme** [comment]
it seems to work as intended, though from the edited README
`  --diamond-args "--sensitive" \`
doesn't seem to be a valid input for humann2 v2.8.1 - it runs fine (so far) w/o that arg.

Thanks a lot for the swift answer

**Comment by nick-youngblut** [comment]
Noted and changed. Thanks!

**Comment by jnesme** [comment]
ok one last thing is that it should probably be:

```
STRUO_OUT_DIR=/home/projects/cu_10108/Databases/humann2_GTDBr89/
NUC_DB=$STRUO_OUT_DIR
PROT_DB=$STRUO_OUT_DIR
MTPHLN_BT2_DB=`dirname /home/projects/cu_10108/people/jnesme/miniconda2/envs/humman2/bin/metaphlan_databases/mpa_v20_m200.1.bt2`
MTPHLN_PKL_DB=/home/projects/cu_10108/people/jnesme/miniconda2/envs/humman2/bin/metaphlan_databases/mpa_v20_m200.pkl
```
rather than pointing explicitely to the files. Humann2 is a sensitive piece of software apparently. :)

**Comment by nick-youngblut** [comment]
I missed that. Thanks! 

Yeah, I'd rewrite humann2 as a snakemake pipeline if I had the time.
