### ISSUE TITLE
contamination still above 5, multiple identical ncbi_organism_name

### ISSUE THREAD

**Issue by NienkeMekkes** [leylabmpi/Struo#10]
Dear Authors,

I ran Rscript util_scripts/GTDB_metadata_filter.R on the latest GTDB bacterial metadata [file](https://data.gtdb.ecogenomic.org/releases/latest/bac120_metadata.tar.gz). I did not change the script, so I used the thresholds for contamination and completeness at <5 and >=50 respectively.

The original file had 191527 lines
After filtering, I have 29450 lines

So far so good. However, when inspecting the filtered file, I noticed 2 things;

1. while completeness is indeed always higher than 50, contamination is not lower than 5. Multiple lines have contamination values of above 400. 
2. even when gtdb_representative is true, multiple rows still have the same value for ncbi_organism_name.

This does not cause any issue when downloading genomes with the other util script, and my Sample_file builds fine. I have a image with a part of this file where issue 1 and 2 are visible. However, when trying to build my kraken/bracken dbs, I get very similar error messages to issue [6](https://github.com/leylabmpi/Struo/issues/6).

<img width="1075" alt="Screenshot 2021-03-24 at 12 50 06" src="https://user-images.githubusercontent.com/26655210/112306526-2cd8e500-8ca0-11eb-9f31-663ad1a84e23.png">

Are these issues as expected? I can easily manually remove the high contamination rows. For issue 2, I saw as solution "merge the assembly id with the NCBI name". However, I don't fully understand what that means, could you give guidance on this?

Thanks in advance

**Comment by nick-youngblut** [comment]
The completeness/contamination values in your table are way outside of what would actually occur. It appears that those columns are lacking decimals; possibly because you are using "," instead of "." for decimals (eg., 9382 for checkm completeness should be 93.82)

**Comment by NienkeMekkes** [comment]
I see, thank you for the clarification. With regards to the second issue of the identical names (for example, chloroflexi bacterium appears 5 times), what would be the best course of action here?

**Comment by nick-youngblut** [comment]
`ncbi_organism_name` is NCBI taxonomy. `gtdb_representative = TRUE` selects based on the GTDB taxonomy

**Comment by NienkeMekkes** [comment]
Thank you Nick. So what I should do in this case, is take the sample file, and merge the column named ncbi_organism_name with the column containing the assembly ID right? That should fix my error in the kraken db creation part?

**Comment by nick-youngblut** [comment]
Yeah, we merged the assembly accession with the ncbi_organism_name. For example:

```
ncbi_organism_name
GB_GCA_002789635.1_Candidatus Aenigmarchaeota archaeon CG_4_9_14_3_um_filter_37_18
GB_GCA_001784635.1_Candidatus Micrarchaeota archaeon RBG_16_49_10
GB_GCA_002254545.1_Candidatus Aenigmarchaeota archaeon ex4484_224
GB_GCA_004297575.1_archaeon
GB_GCA_002688965.1_archaeon
GB_GCA_000806115.1_archaeon GW2011_AR5
GB_GCA_013331845.1_none
GB_GCA_003663225.1_Candidatus Aenigmarchaeota archaeon
GB_GCA_003663415.1_Candidatus Aenigmarchaeota archaeon
```

I'll make that more clear in the README

**Comment by NienkeMekkes** [comment]
perfect, thanks!
