### ISSUE TITLE
Struo fails in building Kraken2 database

### ISSUE THREAD

**Issue by HitMonk** [leylabmpi/Struo#11]
Hello,
I was trying to build a test GTDB database for kraken2. However, when i do run it with struo, i get the following error and im not completely sure what it is referring to:

```
ValueError in line 26 of /exports/watson/Prateek/dbs/struo_gtdb/Struo/Snakefile:
Cannot find column: fasta_file_path
  File "/exports/watson/Prateek/dbs/struo_gtdb/Struo/Snakefile", line 26, in <module>
```
I am also attaching my config.yaml file here. Im just trying to build the kraken2 and bracken databases and skipping humann2 databases. 
Could you please help me out with rectifying this error?

thank you

[config.txt](https://github.com/leylabmpi/Struo/files/6404855/config.txt)

**Comment by nick-youngblut** [comment]
I'm guessing that your `../Files/Test_genomes.txt` table doesn't have a column named `fasta_file_path`

**Comment by HitMonk** [comment]
Ah, yes. I made a mistake in the files that i provided. Apologies for the spam!
