### ISSUE TITLE
Issues with creating kraken2 environment

### ISSUE THREAD

**Issue by HitMonk** [leylabmpi/Struo#12]
I am trying to build the new GTDB database. however, I am running into issues with the kraken2 environment. I already have kraken2 available though, as shown:
```
kraken2 -v
Kraken version 2.1.1
Copyright 2013-2020, Derrick Wood (dwood@cs.jhu.edu)
```
I have also attached the error report here.

Thank you for your support
[screenlog.txt](https://github.com/leylabmpi/Struo/files/6405379/screenlog.txt)

**Comment by nick-youngblut** [comment]
snakemake creates all of the conda envs, including one for kraken2. You should be running snakemake with `--use-conda`. If you run snakemake on a cluster, then you need a profile (see https://github.com/Snakemake-Profiles) with code to activate conda in each cluster job.

**Comment by nick-youngblut** [comment]
> I am trying to build the new GTDB database

I hope that you are just trying to do this for Kraken2, given that you will need some serious computational resources for humann3. 
I will start working on building GTDB-r202 very soon, but the humann3 part of the database construction will likely take a couple of weeks, depending on the amount of gene overlap with those in GTDB-r95.
