### ISSUE TITLE
Are you considering a GTDB 202 release?

### ISSUE THREAD

**Issue by andersgs** [leylabmpi/Struo#13]
Hi. 

Wonderful resource, thank you. I am wondering if you are considering a release with the 202 version of the GTDB database?

Thank you.

Anders.

Release available here: https://data.gtdb.ecogenomic.org/releases/release202/202.0/

**Comment by nick-youngblut** [comment]
It's in progress now. The kraken2/bracken databases are complete, but the humann3 database will take at least a couple of more weeks. I'll upload the kraken2/bracken databases today

**Comment by nick-youngblut** [comment]
Based on limited testing, the kraken2/bracken databases seem to increase % reads mapped by 1-5% (r202 vs r95), at least for human gut microbiomes from westernized populations

**Comment by andersgs** [comment]
Thank you @nick-youngblut

**Comment by nick-youngblut** [comment]
Due to an issue with the gene annotation step, the humann3 database probably won't be ready for another week or so

**Comment by nick-youngblut** [comment]
Available for [Struo2](https://github.com/leylabmpi/Struo2): http://ftp.tue.mpg.de/ebio/projects/struo2/GTDB_release202/
