### ISSUE TITLE
Folder /ebio/abt3_project/Struo/example_build

### ISSUE THREAD

**Issue by sofsta** [leylabmpi/Struo#2]
Hello everyone,

I am following the tutorial and I skipped the first steps: 
`cd /ebio/abt3_projects/Struo/example_build`
`mkdir Files`
`mkdir Genomes`

I just cloned the repo and I set the conda environment. 

When I run the command:
conda activate struo && snakemake --use-conda --create-envs-only

I get the error message 

```
Samples table (Row 1): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_002009845.1/GCA_002009845.1_ASM200984v1_genomic.fna.gz; Skipping
Samples table (Row 2): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000214495.2/GCA_000214495.2_ASM21449v1_genomic.fna.gz; Skipping
Samples table (Row 3): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000221545.2/GCA_000221545.2_ASM22154v1_genomic.fna.gz; Skipping
Samples table (Row 4): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000764165.1/GCA_000764165.1_ASM76416v1_genomic.fna.gz; Skipping
Samples table (Row 5): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_900143645.1/GCA_900143645.1_IMG-taxon_2582580727_annotated_assembly_genomic.fna.gz; Skipping
Samples table (Row 6): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_900205925.1/GCA_900205925.1_Clostridium_peptidoveorans_DPC7177_genomic.fna.gz; Skipping
Samples table (Row 7): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_900176335.1/GCA_900176335.1_IMG-taxon_2588254267_annotated_assembly_genomic.fna.gz; Skipping
Samples table (Row 8): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000755365.1/GCA_000755365.1_ASM75536v1_genomic.fna.gz; Skipping
Samples table (Row 9): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000422585.1/GCA_000422585.1_ASM42258v1_genomic.fna.gz; Skipping
Samples table (Row 10): Cannot find file: /ebio/abt3_projects/databases_no-backup/GTDB/release86/genbank/bacteria/GCA_000298175.1/GCA_000298175.1_ASM29817v1_genomic.fna.gz; Skipping
Total number of skipped rows: 10
ValueError in line 44 of /srv/rs6/sofia/Metoid/Struo-master/Snakefile:
No genomes remaining after filtering!
  File "/path/to/Struo-master/Snakefile", line 44, in <module>

```

So this means that I nead to create a folder /ebio/abt3_projects etc? Or how is this folder created?

Do you have any plans for setting up this pipeline with nextflow as well?

**Comment by nick-youngblut** [comment]
By default, the `config.yaml` points to a table (`tests/samples/samples_n10.txt`) that specifies that paths to the genome fasta files. The paths currently in that `sample_n10.txt` file are set for files on our server, and not yours. You just need to create a new "samples.txt" file with paths to your reference genomes.

@jacodela it would probably be good to change this. We could either have the user download some genomes or provide a few in the repo. I've also put a few genomes on the ftp server: http://ftp.tue.mpg.de/ebio/nyoungblut/genome_data/

**Comment by jacodela** [comment]
@sofsta  thanks for pointing that out. If you have already created the `Struo` conda environment you should be able to skip this step and continue with the tutorial: the conda environment has the R libraries needed to download the test genomes, and once you create a `config.yaml` file with the paths specific to your machine, you should be able to either run the `conda activate struo && snakemake --use-conda --create-envs-only` command or execute the pipeline directly, which will create the environments before starting with the database build. Please note that the `config.yaml` file is now different from what appears in the tutorial. Please modify the file that is located in the main `Struo` folder. I will update the tutorial to reflect these changes.

**Comment by sofsta** [comment]
Thank you both for your replies. Since I am interested in building different custom databases for our pipeline, I will change the config.yaml file accordingly and test again.

I do not have any experience with snakemake and I am planning to use nextflow instead. Do you have any plans of implementing this pipeline in nextflow as well? Or are you aware of any nextflow pipeline implementing something similar?

**Comment by jacodela** [comment]
All of our pipelines are implemented using snakemake, and we don't have current intentions of switching to other workflow manager, sorry. Still, Struo is self-contained, so unless you plan to modify it, using it as currently implemented shouldn't be a problem

**Comment by sofsta** [comment]
@jacodela It worked. I had to modify both config.yaml and config_default.yaml files under tests folder. After I run the command:

` screen -L -S struo_test bash -c "snakemake --use-conda --cores 4"`

I get a folder with the name: Struo_27793069 instead of just Struo.

**Comment by nick-youngblut** [comment]
A couple of things to clarify: 

1. You shouldn't need to use `bash -c`. That's usually only necessary if you are redirecting STDOUT
1. `Struo_27793069` is the temporary output folder, not the final output. The numbers are the directory ID that you ran Struo in. This helps prevent multiple users from trying to write to the same temporary directory

**Comment by sofsta** [comment]
@nick-youngblut Thank you for the clarifications. 

Since there are two config files; the config.yaml and the config_default.yaml under tests/ maybe you can also clarify which one you are using in the tutorial.
