### ISSUE TITLE
error in kraken2_add_taxID

### ISSUE THREAD

**Issue by choon-sim** [leylabmpi/Struo#5]
Hi, I am building the GTDB_release95, and a bug(?) appears in kraken2_add_taxID when I started the workflow. Apparently it tries to assign taxID to multiple genomes at the same time, hence running into error and affecting downstream kraken2_rename_genome.py.

The problem may be that the kraken2_add_taxID script thinks that the taxID is the same among these genomes, but each genome actually has a different GTDB ID uniquely generated using gtdb_to_taxdump and specified in config.yaml.

*note: the genome files will not match between the 2 commands. The whole list is quite long and I am showing only a small subset here.

On another note, how long do you take to run Diamond on a genome? I took 1 hour to run Diamond on 2 genomes on uniRef90 database using 32 cores and 120 Gb memory.

[32m[Thu Jul 23 16:21:28 2020][0m
[32mrule kraken2_add_taxID:
    input: /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900313335.1/GCA_900313335.1_Rumen_uncultured_genome_RUG795_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900313615.1/GCA_900313615.1_Rumen_uncultured_genome_RUG812_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900313705.1/GCA_900313705.1_Rumen_uncultured_genome_RUG837_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900313715.1/GCA_900313715.1_Rumen_uncultured_genome_RUG828_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900313845.1/GCA_900313845.1_Rumen_uncultured_genome_RUG849_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314125.1/GCA_900314125.1_Rumen_uncultured_genome_hRUG883_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314215.1/GCA_900314215.1_Rumen_uncultured_genome_hRUG888_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314335.1/GCA_900314335.1_Rumen_uncultured_genome_hRUG897_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314655.1/GCA_900314655.1_Rumen_uncultured_genome_RUG030_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314715.1/GCA_900314715.1_Rumen_uncultured_genome_RUG036_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314755.1/GCA_900314755.1_Rumen_uncultured_genome_RUG037_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900314985.1/GCA_900314985.1_Rumen_uncultured_genome_RUG062_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900315095.1/GCA_900315095.1_Rumen_uncultured_genome_RUG064_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_900315565.1/GCA_900315565.1_Rumen_uncultured_genome_RUG107_genomic.fna.gz, /gpfs/gsfs6/users
    output: /data/simc/struo/temp/simc/Struo_202883885/uncultured_Prevotellaceae_bacterium.fna
    log: /data/simc/struo/output/logs/kraken2_add_taxID/uncultured_Prevotellaceae_bacterium.log
    jobid: 40242
    benchmark: /data/simc/struo/output/benchmarks/kraken2_add_taxID/uncultured_Prevotellaceae_bacterium.txt
    wildcards: sample=uncultured_Prevotellaceae_bacterium
    resources: time=59, mem_gb_pt=6[0m

kraken2_rename_genome.py: error: unrecognized arguments: /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_002683825.1/GCA_002683825.1_ASM268382v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_002684655.1/GCA_002684655.1_ASM268465v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_002685965.1/GCA_002685965.1_ASM268596v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/bacteria/GCA_002686265.1/GCA_002686265.1_ASM268626v1_genomic.fna.gz ncbi_organism_name

**Comment by nick-youngblut** [comment]
It's snakemake that is trying to provide multiple input genome fasta file instead of just one. The `samples_col` in the `config.yaml` determines individual samples (genomes for individual taxa). If you didn't change the default, then you have replicate `ncbi_organism_name` values in your input table. You need to use unique IDs. You can either create your own unique IDs for each input genome or find another column in the table that has unique IDs.

**Comment by nick-youngblut** [comment]
In regards to the time for processing, yes running diamond on each genome takes a LONG time, especially for UniRef90 (relative to UniRef50). If you don't have access to a large compute cluster, then I don't recommend running Struo on GTDB-r95. It will likely take months to complete.

I'm working on a new, (hopefully) faster algorithm for Struo2 in order to handle the large number of genomes in GTDB-r95, compared to GTDB-r89. If you have any particular ideas on how to speed up the process without loosing annotation accuracy, please let me know!

**Comment by choon-sim** [comment]
Hi @nick-youngblut,
when I changed `ncbi_organism_name` to a unique ID such as `gtdb_taxid`, the workflow does not start at all. Should I be modifying something else?

Here is the Snakefile:
```
rule kraken2_add_taxID:
    """
    Adding a taxononmy ID to the header of each genome.
    Assuming the taxID is in the samples table.
    Writing edited genome to temp dir.

    Format: `kraken:taxid|<taxID>|<seqID>`
    """
    input:
        fasta = lambda wildcards: \
	  config['samples'].loc[wildcards.sample, config['fasta_file_path_col']]
    output:
        temp(config['tmp_dir'] + '{sample}.fna')
    resources:
        time = lambda wildcards, attempt: attempt ** 2 * 59,
        mem_gb_pt = lambda wildcards, attempt: attempt * 6
    params:
        taxID = lambda wildcards: \
	  config['samples'].loc[wildcards.sample, config['taxID_col']].astype(str),
        exe = config['pipeline']['script_folder'] + 'kraken2_rename_genome.py'
    log:
        log_dir + 'kraken2_add_taxID/{sample}.log'
    benchmark:
        benchmark_dir + 'kraken2_add_taxID/{sample}.txt'
    shell:
        """
        {params.exe} {input.fasta} {params.taxID} > {output} 2> {log}
        """
```

**Comment by nick-youngblut** [comment]
You just need unique IDs for the `samples_col`. You could use `uuid` python package to create unique IDs, or do whatever you need to do in order to get non-redundant IDs for each input genome

**Comment by choon-sim** [comment]
sorry I am not so familiar with python. Although I could download `uuid` and followed the examples to generate an ID, I am not too sure how to integrate it with the genome information.

**Comment by nick-youngblut** [comment]
You could use R instead (https://cran.r-project.org/web/packages/uuid/uuid.pdf)

**Comment by choon-sim** [comment]
@nick-youngblut
Hmm, I generated uuid for each genome and called them at `samples_col: 'uuid' ` in `config.yaml`. But the error persists.

`[32mrule kraken2_add_taxID:
    input: /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000006175.2/GCA_000006175.2_ASM617v2_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000007185.1/GCA_000007185.1_ASM718v1_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000007305.1/GCA_000007305.1_ASM730v1_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000007345.1/GCA_000007345.1_ASM734v1_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000008085.1/GCA_000008085.1_ASM808v1_genomic.fna.gz, /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000011085.1/GCA_000011085.1_ASM1108v1_genomic.fna.gz, 
    output: /data/simc/struo/temp/simc/Struo_202883885/987ae348_cdbb_11ea_8e60_4a0006a46c00.fna
    log: /data/simc/struo/output/logs/kraken2_add_taxID/987ae348_cdbb_11ea_8e60_4a0006a46c00.log
    jobid: 5
    benchmark: /data/simc/struo/output/benchmarks/kraken2_add_taxID/987ae348_cdbb_11ea_8e60_4a0006a46c00.txt
    wildcards: sample=987ae348_cdbb_11ea_8e60_4a0006a46c00
    resources: time=59, mem_gb_pt=6[0m`



`usage: kraken2_rename_genome.py [-h] [--version] genome_file taxID
kraken2_rename_genome.py: error: unrecognized arguments: /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000007305.1/GCA_000007305.1_ASM730v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000007345.1/GCA_000007345.1_ASM734v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000008085.1/GCA_000008085.1_ASM808v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000011085.1/GCA_000011085.1_ASM1108v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000011125.1/GCA_000011125.1_ASM1112v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000011185.1/GCA_000011185.1_ASM1118v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000012285.1/GCA_000012285.1_ASM1228v1_genomic.fna.gz /gpfs/gsfs6/users/simc/struo/Genomes/genbank/archaea/GCA_000012545.1/GCA_000012545.1_ASM1254v1_genomic.fna.gz uuid
`

**Comment by nick-youngblut** [comment]
You still don't have one sample per ID, based on the `samples_col`. Otherwise `config['samples'].loc[wildcards.sample, config['fasta_file_path_col']]` would select 1 sample per each run of that rule.

**Comment by choon-sim** [comment]
@nick-youngblut
you are absolutely right. I fixed it. Now with unique IDs per genome, it runs well for my 1000 genome set. Now I am testing it on the 30k genome set.

**Comment by nick-youngblut** [comment]
👏   👍
