### ISSUE TITLE
Struo exits with error

### ISSUE THREAD

**Issue by HitMonk** [leylabmpi/Struo#6]
I have been trying to use Struo to merge GTDB database with other genomes downloaded from NCBI but it always fails with an error. The tests work fine and compile well. This  isnt the case with any genomes that i use. Even if i use just the archaea genomes from gtdb i get an error. Would appreciate any reason why you think this would be happening.   

The snippet of error always reads like this. If i remove the corresponding file where it fails it continues to work until it hits another file with the same error. I have attached the screenlog showing the complete error and the description file. 

`----7 of 6850 steps (0.10%) done
Removing temporary output file ../temp_comp2/prateek/Struo_51390221/prodigal/Thaumarchaeota_archaeon.gbk.
[Wed Aug 26 22:28:00 2020]
Finished job 3928.
8 of 6850 steps (0.12%) done
Removing temporary output file ../temp_comp2/prateek/Struo_51390221/prodigal/none.gbk.
[Wed Aug 26 22:28:13 2020]
Finished job 5706.
9 of 6850 steps (0.13%) done
Removing temporary output file ../temp_comp2/prateek/Struo_51390221/prodigal/Euryarchaeota_archaeon.gbk.
[Wed Aug 26 22:30:03 2020]
Finished job 4352.
10 of 6850 steps (0.15%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Pipeline error! Creating report...
2020-08-26 22:30:03,861 - Parsing log: /exports/watson/Prateek/apps/Struo/.snakemake/log/2020-08-26T222553.322633.snakemake.log
2020-08-26 22:30:03,869 - WARNING: Cannot parse: "    log: /exports/watson/Prateek/dbs/kraken+gtdb/results/logs/kraken2_add_taxID/Candidatus_Bathyarchaeota_archaeon.log (check log file(s) for error message)"
2020-08-26 22:30:03,875 - WARNING: Cannot find rule for snakemake jobID: 4356
2020-08-26 22:30:03,877 - Cannot find qacct log: /var/lib/gridengine/default/common/accounting; Skipping
WARNING: `mutt` not found. Not sending an email
Complete log: /exports/watson/Prateek/apps/Struo/.snakemake/log/2020-08-26T222553.322633.snakemake.log
`

[screenlog.txt](https://github.com/leylabmpi/Struo/files/5134820/screenlog.txt)
[Sample_desc_arch.txt](https://github.com/leylabmpi/Struo/files/5134814/Sample_desc_arch.txt)

**Comment by nick-youngblut** [comment]
You seem to have duplicates in the `ncbi_organism_name` column of your input table. This results in multiple fasta inputs for the `kraken2_add_taxID` rule instead of just one.

**Comment by HitMonk** [comment]
Ah! I see it now. I have about 400 duplicate ids. I guess ill do what you did and merge the assembly id with the NCBI name. That should fix it right?

**Comment by nick-youngblut** [comment]
Yeah, that should work! Reopen if you still have problems
