### ISSUE TITLE
Failure in completing job

### ISSUE THREAD

**Issue by HitMonk** [leylabmpi/Struo#7]
Hello,
I have built and formatted taxonomies as required. I ran a short snippet of the fasta file and it all worked. However, when i tried building a database with the complete set of fasta files i ran into this error. Not sure what it means. Could you please help me out?
`27 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_009731375_1_Paulinella_micropora.gbk.
[Fri Sep 18 15:21:52 2020]
Finished job 168613.
28 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_900893395_1_Euglena_gracilis.gbk.
[Fri Sep 18 15:23:58 2020]
Finished job 166807.
29 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_009767595_1_Symbiodinium_kawagutii.gbk.
[Fri Sep 18 15:24:02 2020]
Finished job 168025.
30 of 206850 steps (0.01%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Pipeline error! Creating report...
2020-09-18 15:24:03,593 - Parsing log: /exports/watson/Prateek/apps/Struo/.snakemake/log/2020-09-18T145213.572283.snakemake.log
2020-09-18 15:24:03,602 - Cannot find qacct log: /var/lib/gridengine/default/common/accounting; Skipping
WARNING: `mutt` not found. Not sending an email
Complete log: /exports/watson/Prateek/apps/Struo/.snakemake/log/2020-09-18T145213.572283.snakemake.log
`

Would you like me to add anyother files?

**Comment by nick-youngblut** [comment]
I'm going to need more information. The output that you provided doesn't actually list the failed job(s). Please at least provide the snakemake log file.

FYI: If you want email notifications when the pipeline is complete (or failed), install `mutt`.

**Comment by HitMonk** [comment]
Im afraid its pretty much the same message on the snakemake log file

`Finished job 166815.
24 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_003297045_1_Symbiodinium_sp_clade_C_Y103.gbk.
[Fri Sep 18 15:19:47 2020]
Finished job 168313.
25 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_003297005_1_Symbiodinium_sp_clade_A_Y106.gbk.
[Fri Sep 18 15:19:52 2020]
Finished job 168327.
26 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_001939145_1_Symbiodinium_microadriaticum.gbk.
[Fri Sep 18 15:20:31 2020]
Finished job 166803.
27 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_009731375_1_Paulinella_micropora.gbk.
[Fri Sep 18 15:21:52 2020]
Finished job 168613.
28 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_900893395_1_Euglena_gracilis.gbk.
[Fri Sep 18 15:23:58 2020]
Finished job 166807.
29 of 206850 steps (0.01%) done
Removing temporary output file ../temp_comp/prateek/Struo_51390221/prodigal/GCA_009767595_1_Symbiodinium_kawagutii.gbk.
[Fri Sep 18 15:24:02 2020]
Finished job 168025.
30 of 206850 steps (0.01%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /exports/watson/Prateek/apps/Struo/.snakemake/log/2020-09-18T145213.572283.snakemake.log`
[2020-09-18T145213.572283.snakemake.log](https://github.com/leylabmpi/Struo/files/5251980/2020-09-18T145213.572283.snakemake.log)

**Comment by nick-youngblut** [comment]
Prodigal is throwing errors and causing snakemake to die. From the snakemake log file:

```
Error in rule prodigal:
    jobid: 164941
    output: ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.fna, ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.faa, ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.gbk
    log: /exports/watson/Prateek/dbs/kraken+gtdb/struo_db/logs/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.log (check log file(s) for error message)
    conda-env: /exports/watson/Prateek/apps/Struo/.snakemake/conda/e2776cc9
    shell:
        
        gunzip -c /exports/watson/Prateek/dbs/kraken+gtdb/library/chlorophyta/GCA_013435795.1_ASM1343579v1_genomic.fna.gz |           prodigal            -o ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.gbk -d ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.fna -a ../temp_comp/prateek/Struo_51390221/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.faa           2> /exports/watson/Prateek/dbs/kraken+gtdb/struo_db/logs/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.log 1>&2
 ```

The log file (`/exports/watson/Prateek/dbs/kraken+gtdb/struo_db/logs/prodigal/GCA_013435795_1_Chlamydomonas_sp_ICE_L.log`) should indicate why prodigal failed.

**Comment by HitMonk** [comment]
is there anyway i can correct this? I would like to only build a kraken2
database. Can i turn prodigal run off? Is it throwing errors because its an
eurkaytotic genome?

**Comment by nick-youngblut** [comment]
The pipeline is designed for prokaryotic genomes. You'd have to edit the pipeline to split the input genomes into prokaryotes & eukaryotes and then annotate genes separately for each group.

**Comment by HitMonk** [comment]
Huh, that doesnt sound like a trivial thing to do... Is there a way i can
just provide it with all the annotations for the eukaryotic genomes? Any
possibility to just provide them as a bunch of paths?
